### ISSUE TITLE
Why not to use cmake source code instead?

### ISSUE THREAD

**Issue by hinell** [Decodetalkers/neocmakelsp#14]
Hi. I'm surpised that you use rust instead of C++ to develop this LSP server. It's reasonable to use CMake source code base instead of trying to port its features to inherently incompatible language. Is there motivation behind this?

**Comment by Decodetalkers** [comment]
Languager server is just about ast,  search packages and complete , it is just analyze the text, so any languages are possible, and it is easy for rust to develop language server

**Comment by hinell** [comment]
It would be best IMHO to reuse existing codebase in order to avoid maintenance burden.

**Comment by hinell** [comment]
It would be best IMHO to reuse existing codebase in order to minimize maintenance burden.

**Comment by Decodetalkers** [comment]
This program use treesitter to handle cmake ast,  cmake repo is too big, and no one really like to develop in cpp
