### ISSUE TITLE
Formatting in case of structured multi-value args worsened

### ISSUE THREAD

**Issue by alex1701c** [Decodetalkers/neocmakelsp#16]
```cmake
ecm_setup_qtplugin_macro_names(
    JSON_NONE
        "K_PLUGIN_FACTORY"
        "K_PLUGIN_CLASS"
    JSON_ARG2
        "K_PLUGIN_FACTORY_WITH_JSON"
        "K_PLUGIN_CLASS_WITH_JSON"
    CONFIG_CODE_VARIABLE
        PACKAGE_SETUP_AUTOMOC_VARIABLES
)
```
Would get turned into:

```cmake
ecm_setup_qtplugin_macro_names(
    JSON_NONE
    "K_PLUGIN_FACTORY"
    "K_PLUGIN_CLASS"
    JSON_ARG2
    "K_PLUGIN_FACTORY_WITH_JSON"
    "K_PLUGIN_CLASS_WITH_JSON"
    CONFIG_CODE_VARIABLE
    PACKAGE_SETUP_AUTOMOC_VARIABLES
)
```

This hurts readability, because one has a harder time realizing to which are argument names and what are the values.

Do you think sth. like this could be detectable/fixable? 

Besides that the results are amazing, thanks for your effort!

**Comment by Decodetalkers** [comment]
You can use #Not Format Me commit, as what clang-format do

**Comment by Decodetalkers** [comment]
https://github.com/Decodetalkers/neocmakelsp/blob/master/test/CMakeLists.txt#L249 

For example

**Comment by alex1701c** [comment]
Thanks for the fast response! I was hoping to not disable formatting entirely for such a block, because the automatic removal of e.g. trailing spaces is still useful.

I wonder to what degree we could automatically detect multi value keys. Might be them being a literal without quotes be a good enough heuristic?

**Comment by alex1701c** [comment]
```cmake
# Not Format Me 
ecm_setup_qtplugin_macro_names(
    JSON_NONE
        "K_PLUGIN_FACTORY"
        "K_PLUGIN_CLASS"
    JSON_ARG2
        "K_PLUGIN_FACTORY_WITH_JSON"
        "K_PLUGIN_CLASS_WITH_JSON"
    CONFIG_CODE_VARIABLE
        PACKAGE_SETUP_AUTOMOC_VARIABLES
)
```

Hmm, though here it is reformatted anyway. I have version 0.5.18 installed through nvim.

**Comment by Decodetalkers** [comment]
> 

![image](https://github.com/Decodetalkers/neocmakelsp/assets/60290287/338f4da0-3a73-42ae-ba17-2bb53eb0c693)
sorry, this format is stupid enough, you need to remove that space

**Comment by alex1701c** [comment]
Oh, makes sense

**Comment by alex1701c** [comment]
Another issue I encountered is that `...neocmakelsp/bin/neocmakelsp -F -o CMakeLists.txt` appears to ignore the editorconfig.

Opening the file in nvim and just pressing leader+w, my configured tabwidth of 4 spaces is used when reformatting. Though in case I have opened+saved the file with the changes from the previous command, the indent is kept. Only when setting "# vi:expandtab:tabstop=4 shiftwidth=4:" in the file and reopening it, it gets changed to 4 spaces again.

**Comment by Decodetalkers** [comment]
> Another issue I encountered is that `...neocmakelsp/bin/neocmakelsp -F -o CMakeLists.txt` appears to ignore the editorconfig.
> 
> Opening the file in nvim and just pressing leader+w, my configured tabwidth of 4 spaces is used when reformatting. Though in case I have opened+saved the file with the changes from the previous command, the indent is kept. Only when setting "# vi:expandtab:tabstop=4 shiftwidth=4:" in the file and reopening it, it gets changed to 4 spaces again.

https://github.com/Decodetalkers/neocmakelsp/blob/master/src/languagerserver.rs#L271

it you use space, it will read the size, or it will format with tab with one length. the size is sent by editor, 

and before... when it format, it will read the .editconfig file in the root dir, if  you have not put the file in root dir, I think it cannot read, and it takes .editconfig as ini, but I don't think it is right? maybe you can help debug it

**Comment by Decodetalkers** [comment]
I am worry that if it is
```cmake
#begin format off
set(A
 B
#end format off
C
 D
   E
)
```

I think it will be quite hard to handle it

**Comment by alex1701c** [comment]
Yeah, implementing it everywhere seems more difficult. Or one could have a look at https://cmake-format.readthedocs.io/en/latest/format-features.html#custom-commands. Unfortunately, the project seems unmaintained.

Another idea: Could one add a config option for excluding specific functions? In my case, I would exclude ecm_setup_qtplugin_macro_names, ecm_add_qch and ecm_generate_headers. That would solve most of my issues in one central place.

I can understand if this exceeds the work you can/want to put into this. In the worst case, I'll manually format the files and revert unreasonable changes. Having `# Not Format Me` in many places if neocmakelsp is not an official tool for the projects I work on doesn't feel right.

**Comment by Decodetalkers** [comment]
I will refactor this part next week. I think I just keep the tab from the second line, just  trim it is ok

**Comment by alex1701c** [comment]
But you'd still check if the indentation uses the correct amount of spaces in case one has that configured? I sometimes see code where few statements have an indent of two and all other ones 4.

**Comment by Decodetalkers** [comment]
https://github.com/Decodetalkers/neocmakelsp/pull/19

now the format is just trim instead, it will keep the tab , only if it is the first line of the command

**Comment by alex1701c** [comment]
Thanks! I will try out soonish :)

**Comment by alex1701c** [comment]
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f73afa65..7e0b9c57 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,6 +1,6 @@
 cmake_minimum_required(VERSION 3.16)
 
-set(KF_VERSION "5.240.0") # handled by release scripts
+set(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scripts
 project(KCoreAddons VERSION ${KF_VERSION})
 
 include(FeatureSummary)
@@ -92,14 +92,14 @@ if (BSDLIKE)
     endif()
 endif()
````

After formatting the same files again, lines with comments are growing with each format

**Comment by Decodetalkers** [comment]
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index f73afa65..7e0b9c57 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -1,6 +1,6 @@
>  cmake_minimum_required(VERSION 3.16)
>  
> -set(KF_VERSION "5.240.0") # handled by release scripts
> +set(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scriptsset(KF_VERSION "5.240.0") # handled by release scripts
>  project(KCoreAddons VERSION ${KF_VERSION})
>  
>  include(FeatureSummary)
> @@ -92,14 +92,14 @@ if (BSDLIKE)
>      endif()
>  endif()
> ```
> 
> After formatting the same files again, lines with comments are growing with each format

fixed : https://github.com/Decodetalkers/neocmakelsp/commit/618859a54f3248cf0413d5868952311f39e2ef46

**Comment by alex1701c** [comment]
With the updated version, I noticed it "eating" comments:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f73afa65..8779b286 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -65,7 +65,7 @@ set(HAVE_FAM ${FAM_FOUND})
 
 option(ENABLE_INOTIFY "Try to use inotify for directory monitoring" ON)
 if(ENABLE_INOTIFY)
-    # Find libinotify
+
     find_package(Inotify)
     set_package_properties(Inotify PROPERTIES
         PURPOSE "Filesystem alteration notifications using inotify")
```

**Comment by Decodetalkers** [comment]
fixed

**Comment by alex1701c** [comment]
Sorry to say, but there is still/again an issue with comments :sweat_smile: 

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f73afa65..edb2d384 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -92,7 +92,7 @@ if (BSDLIKE)
     endif()
 endif()
 
-if(NOT WIN32) # never relevant there
+if(NOT WIN32) # never relevant there    if(NOT WIN32) # never relevant there
     find_package(Qt6DBus ${QT_MIN_VERSION} CONFIG)
     set(HAVE_QTDBUS ${Qt6DBus_FOUND})
     add_feature_info(XDGPortalDragAndDrop HAVE_QTDBUS "Drag and Drop support via xdg-desktop-portal requies QtDBus")
```

**Comment by Decodetalkers** [comment]
> Sorry to say, but there is still/again an issue with comments sweat_smile
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index f73afa65..edb2d384 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -92,7 +92,7 @@ if (BSDLIKE)
>      endif()
>  endif()
>  
> -if(NOT WIN32) # never relevant there
> +if(NOT WIN32) # never relevant there    if(NOT WIN32) # never relevant there
>      find_package(Qt6DBus ${QT_MIN_VERSION} CONFIG)
>      set(HAVE_QTDBUS ${Qt6DBus_FOUND})
>      add_feature_info(XDGPortalDragAndDrop HAVE_QTDBUS "Drag and Drop support via xdg-desktop-portal requies QtDBus")
> ```

can you test it with the last commit? I think I fix it

**Comment by Decodetalkers** [comment]
hello, can you compile the git version code? if there is other problem, I can fix them soon

**Comment by alex1701c** [comment]
I have compiled the git version for all your related commits to this issue. I haven't seen any regressions regarding the formatting. Thanks for your effort!
