### ISSUE TITLE
Ability to disable formatting

### ISSUE THREAD

**Issue by thetic** [Decodetalkers/neocmakelsp#20]
I do not want to use the formatting capability of neocmakelsp, both as a matter of taste and because it can break the code. Is there a configuration option to disable it?

**Comment by Decodetalkers** [comment]
I do not want to induce other config file to a project, but this is possible, let me thought about it.. But I think you can disable auto format of lsp, I do not think it is a right config, I think this should do in you config, lsp format will work only if you request, I think you make it work after every time save your file

**Comment by Decodetalkers** [comment]
does this solve your problem?

https://github.com/Decodetalkers/neocmakelsp/pull/21

**Comment by thetic** [comment]
I agree that a config file is too much. I was thinking about adding adding a setting to `nvim_lsp.neocmake.setup` arguments.

**Comment by Decodetalkers** [comment]
https://github.com/Decodetalkers/neocmakelsp/pull/22 

fixed, I add it to init_options

**Comment by Decodetalkers** [comment]
what do you think about the config?  Do you think "format" is enough? or change it to enable_format?

**Comment by thetic** [comment]
maybe

```
formatting = {
  enable = true
}
```

in case you add other options later?

**Comment by Decodetalkers** [comment]
Ok , the option now is 
```
format = {
  enable = true
}
```

**Comment by Decodetalkers** [comment]
it you think the option is not good enough, you can post pr or continue this issue. I will make a release this night

**Comment by Decodetalkers** [comment]
Since the option is added, so can we close this issue? And this repo need some help,like make the package search works on macos, do you have interested in it?

**Comment by Decodetalkers** [comment]
Ok, I close this issue, thanks for your issue again
