### ISSUE TITLE
Format file doesn't work on my machine

### ISSUE THREAD

**Issue by sdifru** [Decodetalkers/neocmakelsp#23]
I follow the instruction [here](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#neocmake). This is my config:
`require'lspconfig'.neocmake.setup{}`

When I run `:Format` or `:FormatWrite`, the `CMakeLists.txt` doesn't get formatted.

**Comment by Decodetalkers** [comment]
```
   vim.keymap.set("n", "<space>f", function() 
         vim.lsp.buf.format({ async = true }) 
     end, bufopts)
```

If you want to use lsp format, you need use `vim.lsp.bud.formar`

**Comment by sdifru** [comment]
Ah, does lsp format means a formatter which come with an lsp?
yes, I've used these lines and configured it to use lsp format:
```
vim.keymap.set("n", "<space>f", function() 
        vim.lsp.buf.format({ async = true }) 
    end, bufopts)
```
When I pressed `<space>f`, it looked like it does something to the file but the file was not formatted.
I've also run `neocmakelsp format CMakeLists.txt`. It printed the exact same text. It didn't format it.

**Comment by Decodetalkers** [comment]
> Ah, does lsp format means a formatter which come with an lsp? yes, I've used these lines and configured it to use lsp format:
> 
> ```
> vim.keymap.set("n", "<space>f", function() 
>         vim.lsp.buf.format({ async = true }) 
>     end, bufopts)
> ```
> 
> When I pressed `<space>f`, it looked like it does something to the file but the file was not formatted. I've also run `neocmakelsp format CMakeLists.txt`. It printed the exact same text. It didn't format it.

have you try to add some tabs? And as I have noted in README.md, it do very little format, just do replace tab with space or space with tab, replace one tab to two tabs

**Comment by sdifru** [comment]
> have you try to add some tabs? And as I have noted in README.md, it do very little format, just do replace tab with space or space with tab, replace one tab to two tabs

Yes, it works. I thought it would work like cmake-format. Thanks.

**Comment by Decodetalkers** [comment]
> > have you try to add some tabs? And as I have noted in README.md, it do very little format, just do replace tab with space or space with tab, replace one tab to two tabs
> 
> Yes, it works. I thought it would work like cmake-format. Thanks.

This because a kde developer think cmake format should not do too much thing, because lot of format is controled by writter, and I agreed with him, so not it just do trim, remove useless space and just correct the space size of the first line. So other place I think it should be controlled by author
