### ISSUE TITLE
Keep newlines at end of file

### ISSUE THREAD

**Issue by alex1701c** [Decodetalkers/neocmakelsp#25]
When formatting files, git diff says "\ No newline at end of file". I prefer to always have a newline at the file end. At least that is what all projects I am working on use.

**Comment by Decodetalkers** [comment]
Does it mean the last char of the buffer is '\n'? Then I have tried to fix it.. in the newest commit

**Comment by Decodetalkers** [comment]
https://github.com/Decodetalkers/neocmakelsp/commit/dd06d5365970c731e27404b3250d536869704c3c can you take a try?

**Comment by Decodetalkers** [comment]
Ok, I will make a new tag, I think I have already handle it

**Comment by alex1701c** [comment]
/home/user/projects/neocmakelsp/target/debug/neocmakelsp -F -o CMakeLists.txt

That does not seem to work with the CMakeLists.txt of lets say https://invent.kde.org/frameworks/kcoreaddons/-/blob/master/CMakeLists.txt?ref_type=heads


```diff
-kde_configure_git_pre_commit_hook(CHECKS CLANG_FORMAT)
+kde_configure_git_pre_commit_hook(CHECKS CLANG_FORMAT)
\ No newline at end of file
```

**Comment by Decodetalkers** [comment]
Fixed, and I add unit test

**Comment by alex1701c** [comment]
Can confirm, thanks!
