### ISSUE TITLE
False positive diagnostic for `include` 

### ISSUE THREAD

**Issue by uyha** [Decodetalkers/neocmakelsp#27]
with the following snippet
```cmake
include("${CMAKE_SOURCE_DIR}/random.cmake")
```
`neocmakelsp` will produce a warning saying
>include file does not exist or is inaccessible

even if there is a `random.cmake` file

**Comment by Decodetalkers** [comment]
Emmm, I cannot know what the value is. Maybe it there is a value, I should pass the check?

**Comment by Decodetalkers** [comment]
And it is just a warning, I think

**Comment by Decodetalkers** [comment]
Ok, I will skip to check this file, and it will not report warning anymore

**Comment by Decodetalkers** [comment]
Can you take a try? just build it.

**Comment by uyha** [comment]
could you publish a release? I'm using `mason` to install the LSP so it's not easy to switch to a custom build

**Comment by Decodetalkers** [comment]
Ok, I have publish one

**Comment by uyha** [comment]
yes, this is fixed, but i do wonder why you can't dereference for the value of "${CMAKE_SOURCE_DIR}"

**Comment by Decodetalkers** [comment]
because I do not know how to do
