### ISSUE TITLE
Not work on debian, mac and windows

### ISSUE THREAD

**Issue by Decodetalkers** [Decodetalkers/neocmakelsp#3]
x86_64-linux-gnu file is not supported
the directroy of mac is also not supported
and also windows

**Comment by Jackson-soft** [comment]
Have you considered compiling binaries?

**Comment by Decodetalkers** [comment]
> Have you considered compiling binaries?

What is this about, I will happy to realize this, but now I need help , I don't work on mac or windows =_=

**Comment by Jackson-soft** [comment]
> 

https://docs.github.com/en/actions/using-workflows/about-workflows

**Comment by Decodetalkers** [comment]
> I think this documentation might be helpful.
> 
> > 
> 
> https://docs.github.com/en/actions/using-workflows/about-workflows

You can make a pull request, but I don't think workflow is needed now, since there are other works to do ..

**Comment by Jackson-soft** [comment]
Currently only ubuntu can compile successfully，macos and windows failed.

**Comment by Decodetalkers** [comment]
> Currently only ubuntu can compile successfully，macos and windows failed.

https://github.com/Decodetalkers/neocmakelsp/blob/master/src/utils/findpackage/packagemac.rs here, it is empty, so sure, it cannot be compile

**Comment by Decodetalkers** [comment]
> Currently only ubuntu can compile successfully，macos and windows failed.

ci fixed, now , just fixed. emm

**Comment by alven-shin** [comment]
Is this issue still relevant? Neocmakelsp compiles and seems to work fine on MacOS. I do not use Windows, so I cannot say anything about that.

**Comment by Decodetalkers** [comment]
> Is this issue still relevant? Neocmakelsp compiles and seems to work fine on MacOS. I do not use Windows, so I cannot say anything about that.

Windows I add basic support, but I do not use windows, and also do not really know how to findpackage on windows.. 

Mac I think it will works, but it cannot find package under homebrew, or some cmake package in Mac specific.. so it can be compiled and run on them, but maybe some feature is not run well

**Comment by alven-shin** [comment]
Ahh I see, thanks for your response.
