### ISSUE TITLE
feature request: provide package prebuilt with static musl

### ISSUE THREAD

**Issue by yangyingchao** [Decodetalkers/neocmakelsp#31]
If server is linked with static musl library, we can run it in OS shipped with older version of glibc.

The current server fails to start under centos 7, with error:

```
./neocmakelsp-x86_64-unknown-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by ./neocmakelsp-x86_64-unknown-linux-gnu)                                                                                           
````

Regards.

**Comment by Decodetalkers** [comment]
Emm. I am not good at ci.. maybe you can help add one

**Comment by yangyingchao** [comment]
PR #32 , only for linux. :)
