### ISSUE TITLE
Temporarily  disable formatting like clangd

### ISSUE THREAD

**Issue by Sologala** [Decodetalkers/neocmakelsp#33]
Is there some pattern in code to temporarily disable cmake-format, like `clangd-format off`

```cmake
CPMAddPackage("gh:fmtlib/fmt#7.1.3")
```
`neocmakelsp` will format the code above to 

```cmake
 CPMAddPackage("gh:fmtlib/fmt #7.1.3")
```

**Comment by Decodetalkers** [comment]
It is a bug and should be fixed

**Comment by Decodetalkers** [comment]
https://github.com/Decodetalkers/neocmakelsp/blob/master/src%2Fformatting.rs#L13

Bug is here

**Comment by Sologala** [comment]
@Decodetalkers  Thk for fixing, I will update my lazy config and try it. 
BTW, do `neocmakelsp` formatting has the some keyword to locally disable formatting?

**Comment by Decodetalkers** [comment]
> @Decodetalkers  Thk for fixing, I will update my lazy config and try it. 
> BTW, do `neocmakelsp` formatting has the some keyword to locally disable formatting? 

It has in the past, but now it doesn't. As I said in readme, neocmakelsp now will not do too much format, it just does trim, so if there be weird format, it must be the bug of neocmakelsp

**Comment by Sologala** [comment]
OK, I got it.

**Comment by Decodetalkers** [comment]
Emm, this still be the issue, I should reopen it, now I have fixed it right now

**Comment by Decodetalkers** [comment]
Can you confirm if it is fixed?

**Comment by Decodetalkers** [comment]
ok, if there is any problems, welcome to open this issue again
