### ISSUE TITLE
[feature] Shell completion

### ISSUE THREAD

**Issue by Freed-Wu** [Decodetalkers/neocmakelsp#38]
Can it provide completions for common shells?

TIA!

**Comment by Decodetalkers** [comment]
Ok, please!

**Comment by Freed-Wu** [comment]
```sh
$ neocmakelsp <TAB>
# or
$ neocmakelsp --<TAB>
```

**Comment by Decodetalkers** [comment]
> ```sh
> $ neocmakelsp <TAB>
> # or
> $ neocmakelsp --<TAB>
> ```

Ohh, I see, then it needs to be packaged to linux distributions. And maybe zsh of fish completion files? You can help me add some. Thanks

**Comment by Freed-Wu** [comment]
Oh, I notice this program is written in rust. So I guess [clap](https://docs.rs/clap_complete/latest/clap_complete/) can be helpful?

**Comment by Decodetalkers** [comment]
> Oh, I notice this program is written in rust. So I guess [clap](https://docs.rs/clap_complete/latest/clap_complete/) can be helpful?

This program has already used clap, but these options are inside the program, shell will never know

**Comment by Freed-Wu** [comment]
> shell will never know

It looks like `cargo build` will generate those shell completion scripts, then they

> be packaged to linux distributions

https://gitlab.archlinux.org/archlinux/packaging/packages/eza/-/blob/main/PKGBUILD?ref_type=heads#L48-50

**Comment by Decodetalkers** [comment]
> > shell will never know
> 
> It looks like `cargo build` will generate those shell completion scripts, then they
> 
> > be packaged to linux distributions
> 
> https://gitlab.archlinux.org/archlinux/packaging/packages/eza/-/blob/main/PKGBUILD?ref_type=heads#L48-50

https://github.com/eza-community/eza/blob/main/completions/zsh/_eza

Like eza, the completions is written by hands, not by cargo, cargo will not do such kind of things

**Comment by Freed-Wu** [comment]
Interesting. I need to take a look at some similar projects before answering this question.

**Comment by Decodetalkers** [comment]
ok, I have add a fish completion. because I only use fish

**Comment by Decodetalkers** [comment]
ok, fish and zsh is generated
