### ISSUE TITLE
cmake format failed due to a information

### ISSUE THREAD

**Issue by Freed-Wu** [Decodetalkers/neocmakelsp#40]
I met:

```json
[coc.nvim] Connection to server cmake language server is erroring, Header must provide a Content-Length property.
{"\u001b[2m2024-04-03t05":"43:18.470596Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[2mneocmakelsp::languageserver\u001b[0m\u001b[2m:\u001b[0m \u001b[3minput.options.insert_spaces\u001b[0m\u001b[2m=\u001b[0mtrue\nContent-Length: 88"}. Shutting down server.
```

It is:

```
43:18.470596Z  INFO neocmakelsp::languageserver: input.options.insert_spaces=true
```

I think changing this message's level from `INFO` to `DEBUG` can fix this issue.

Environment:

- [coc-cmake](https://www.npmjs.com/package/coc-cmake) 0.2.2
- neocmakelsp 0.6.20

**Comment by Decodetalkers** [comment]
No, this is not related.. I do not use coc, I use nvim-lsp, it always works fine

**Comment by fannheyward** [comment]
@Freed-Wu what do you mean `change INFO to DEBUG`?

**Comment by fannheyward** [comment]
coc.nvim uses vscode-jsonrpc that checks `Content-Length` header 

https://github.com/microsoft/vscode-languageserver-node/blob/46f6f9038fee60dbdfeb5307201397adc8feb3cb/jsonrpc/src/common/messageReader.ts#L223-L227

**Comment by Decodetalkers** [comment]
Maybe coc want to invoke the format action of cmake-lanaguage-server? Maybe it doesn't invoked neocmakelsp

**Comment by Freed-Wu** [comment]
> coc want to invoke the format action of cmake-lanaguage-server? 

No, it will call `neocmakelsp` https://github.com/voldikss/coc-extensions/blob/main/packages/coc-cmake/package.json#L55

**Comment by Freed-Wu** [comment]
> coc.nvim uses vscode-jsonrpc

Yes, it looks vscode-jsonrpc have some different behaviour from nvim's json rpc?

**Comment by Decodetalkers** [comment]
https://github.com/Decodetalkers/neocmakelsp/blob/master/src/languageserver.rs#L327-L333

seems it does go to the formatting, but it failed in coc.. can you see the log of `formating`?

**Comment by Freed-Wu** [comment]
Just decrease verbosity to not output the INFO message to stdout will fix it :smile:

**Comment by Decodetalkers** [comment]
oh.. you can make a pr for it, that place should not use tracing::info... it is a mistake

**Comment by Freed-Wu** [comment]
I am not familiar with rust currently and I am afraid of doing something wrong :cry:

**Comment by Decodetalkers** [comment]
ok..

**Comment by Decodetalkers** [comment]
May I close this issue since it is fixed
