### ISSUE TITLE
Support upper keyword

### ISSUE THREAD

**Issue by Freed-Wu** [Decodetalkers/neocmakelsp#45]
cmake keyword can be upper. such as `CMAKE_MINIMUM_REQUIRED()`.

## Expected behaviour

document hover can work for `CMAKE_MINIMUM_REQUIRED`. When it detect upper keyword, it will complete upper keyword (`STRING` not `string`)

## Actual behaviour

Doesn't support now.

**Comment by Decodetalkers** [comment]
![image](https://github.com/Decodetalkers/neocmakelsp/assets/60290287/d9d959c8-455e-4cbd-9e32-a8e0f15b89c3)

Emm, it should be supported I think

**Comment by Decodetalkers** [comment]
oh.. I see. complete one
