### ISSUE TITLE
`neocmakelsp format override .` does nothing

### ISSUE THREAD

**Issue by multivac61** [Decodetalkers/neocmakelsp#49]
I have a C++/CMake monorepo and would like to use your package to format the code. I have unformatted `CMakeLists.txt` and `*.cmake` files but running `neocmakelsp format override .` does nothing does nothing.

I've tried both installing/running on `aarch64-darwin` and x86_64-linux.

What am I doing wrong?

**Comment by Decodetalkers** [comment]
`neocmakelsp --format -o .`

try this one

**Comment by multivac61** [comment]
Ah, so you provide it with a list of files? It will not search recursively for `CMakeLists.txt` and `*.cmake` files?

**Comment by Decodetalkers** [comment]
Emmm, I mean --format receive files or `override` short parm. So if you use 'override', clap will think of it as file

**Comment by multivac61** [comment]
Ah, I see, it is treating `override` as a path?

**Comment by multivac61** [comment]
Is there no way to pass a path into the program and have it scan for standard cmake files?

**Comment by multivac61** [comment]
There is a bug somewhere.. see my video.

![CleanShot 2024-05-21 at 13 08 54](https://github.com/Decodetalkers/neocmakelsp/assets/4436129/acaea032-6b01-4063-8e78-23fd6118ab30)

**Comment by Decodetalkers** [comment]
Can I see your .gitignore? it there is not .gitignore, will it be formatted? 

try not add -o, it will print the formatted content

**Comment by multivac61** [comment]
Removing the `.gitignore` solved the issue...

```
# Prerequisites
*.d

# Compiled Object files
*.slo
*.lo
*.o
*.obj

# Precompiled Headers
*.gch
*.pch

# Compiled Dynamic libraries
*.so
*.dylib
*.dll

# Fortran module files
*.mod
*.smod

# Compiled Static libraries
*.lai
*.la
*.a
*.lib

# Executables
*.exe
*.out
*.app

# Application state
*.xml

# Temporary folders
build/
scripts/geerated_fft_window.h

# SublimeText stuff
*.sublime*

# JetBrains / CLion stuff
.idea

.DS_STORE

# Autogenerated files
Builds/
JuceLibraryCode/AppConfig.h
JuceLibraryCode/BinaryData*
cmake-build*

# Copied after Emscripte build
extra/quarks/web/tests/cpp/*.js

venv

dsa_priv.pem
sparkle
sparkle_updates
.vs

__pycache__

# CMake stuff
CMakeUserPresets.json
.fetched_content/

# Spectrogram test data
firmwave/firmware_test/tests/spectrogram_test_data.cpp 

.cpm*

build-*/

# nix related
result
.direnv
.envrc.local
```

**Comment by Decodetalkers** [comment]
I have bad handle to solve the .gitignore.. so it is a known bug, I do not knwo what make it ignore the file..

**Comment by Decodetalkers** [comment]
can you try the master branch to see if it solve the problem of gitgnore?

**Comment by multivac61** [comment]
At least the files get formatted 👍 

There are however a bunch of `:Permission denied (os error 13)` errors on files that are in my `.gitignore` and path...

**Comment by Decodetalkers** [comment]
Seems the gitignore is still not handled right, emmmm

**Comment by Decodetalkers** [comment]
Haa. fixed, I will publish a new release

**Comment by Decodetalkers** [comment]
https://github.com/Decodetalkers/neocmakelsp/commit/9c7629c506553dea404702dbe7fe44e7acd7ad80

I made a mistake. I return none, when gitignore is added successfully

**Comment by Decodetalkers** [comment]
Ok, I think I have fixed it, if the problem comes again, please to open this issue again. Thanks for your report!!
