### ISSUE TITLE
v0.4.5 can not compile on windows msvc

### ISSUE THREAD

**Issue by Logiase** [Decodetalkers/neocmakelsp#5]
stable-msvc toolchain

error message:
```text
error[E0432]: unresolved import `crate::utils::CMAKE_PACKAGES`
 --> C:\Users\Logiase\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\neocmakelsp-0.4.5\src\search.rs:1:5
  |
1 | use crate::utils::CMAKE_PACKAGES;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `CMAKE_PACKAGES` in `utils`

error[E0425]: cannot find value `CMAKE_PACKAGES` in module `utils`
 --> C:\Users\Logiase\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\neocmakelsp-0.4.5\src\complete\findpackage.rs:5:12
  |
5 |     utils::CMAKE_PACKAGES
  |            ^^^^^^^^^^^^^^ not found in `utils`

error[E0425]: cannot find value `CMAKE_PACKAGES_WITHKEY` in module `utils`
  --> C:\Users\Logiase\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\neocmakelsp-0.4.5\src\jump\findpackage.rs:10:12
   |
10 |     utils::CMAKE_PACKAGES_WITHKEY.get(&input).map(|context| {
   |            ^^^^^^^^^^^^^^^^^^^^^^ not found in `utils`

Some errors have detailed explanations: E0425, E0432.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `neocmakelsp` due to 3 previous errors
error: failed to compile `neocmakelsp v0.4.5`, intermediate artifacts can be found at `C:\Users\Logiase\AppData\Local\Temp\cargo-installMBLtb6`
```

**Comment by Decodetalkers** [comment]
> stable-msvc toolchain
> 
> error message:
> 
> ```
> error[E0432]: unresolved import `crate::utils::CMAKE_PACKAGES`
>  --> C:\Users\Logiase\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\neocmakelsp-0.4.5\src\search.rs:1:5
>   |
> 1 | use crate::utils::CMAKE_PACKAGES;
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `CMAKE_PACKAGES` in `utils`
> 
> error[E0425]: cannot find value `CMAKE_PACKAGES` in module `utils`
>  --> C:\Users\Logiase\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\neocmakelsp-0.4.5\src\complete\findpackage.rs:5:12
>   |
> 5 |     utils::CMAKE_PACKAGES
>   |            ^^^^^^^^^^^^^^ not found in `utils`
> 
> error[E0425]: cannot find value `CMAKE_PACKAGES_WITHKEY` in module `utils`
>   --> C:\Users\Logiase\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\neocmakelsp-0.4.5\src\jump\findpackage.rs:10:12
>    |
> 10 |     utils::CMAKE_PACKAGES_WITHKEY.get(&input).map(|context| {
>    |            ^^^^^^^^^^^^^^^^^^^^^^ not found in `utils`
> 
> Some errors have detailed explanations: E0425, E0432.
> For more information about an error, try `rustc --explain E0425`.
> error: could not compile `neocmakelsp` due to 3 previous errors
> error: failed to compile `neocmakelsp v0.4.5`, intermediate artifacts can be found at `C:\Users\Logiase\AppData\Local\Temp\cargo-installMBLtb6`
> ```

It used to be, but now it will be compiled... but can just run..

**Comment by Decodetalkers** [comment]
> stable-msvc toolchain
> 
> error message:
> 
> ```
> error[E0432]: unresolved import `crate::utils::CMAKE_PACKAGES`
>  --> C:\Users\Logiase\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\neocmakelsp-0.4.5\src\search.rs:1:5
>   |
> 1 | use crate::utils::CMAKE_PACKAGES;
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `CMAKE_PACKAGES` in `utils`
> 
> error[E0425]: cannot find value `CMAKE_PACKAGES` in module `utils`
>  --> C:\Users\Logiase\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\neocmakelsp-0.4.5\src\complete\findpackage.rs:5:12
>   |
> 5 |     utils::CMAKE_PACKAGES
>   |            ^^^^^^^^^^^^^^ not found in `utils`
> 
> error[E0425]: cannot find value `CMAKE_PACKAGES_WITHKEY` in module `utils`
>   --> C:\Users\Logiase\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\neocmakelsp-0.4.5\src\jump\findpackage.rs:10:12
>    |
> 10 |     utils::CMAKE_PACKAGES_WITHKEY.get(&input).map(|context| {
>    |            ^^^^^^^^^^^^^^^^^^^^^^ not found in `utils`
> 
> Some errors have detailed explanations: E0425, E0432.
> For more information about an error, try `rustc --explain E0425`.
> error: could not compile `neocmakelsp` due to 3 previous errors
> error: failed to compile `neocmakelsp v0.4.5`, intermediate artifacts can be found at `C:\Users\Logiase\AppData\Local\Temp\cargo-installMBLtb6`
> ```

https://github.com/Decodetalkers/neocmakelsp/blob/master/src/utils/findpackage/packagewin.rs

As you have seen , empty.. Because I am not using windows

**Comment by Decodetalkers** [comment]
emmm,你来帮我写

**Comment by Logiase** [comment]
> emmm,你来帮我写

唐突中文）

**Comment by Decodetalkers** [comment]
> > emmm,你来帮我写
> 
> 唐突中文）

因为突然发现是熟人

**Comment by Logiase** [comment]
> > > emmm,你来帮我写
> > 
> > 
> > 唐突中文）
> 
> 因为突然发现是熟人

怎么到处都是HITLUG人

**Comment by Decodetalkers** [comment]
所以我真的不是很熟悉windows的逻辑，真的希望你能帮我完善。。以及还有其他的一些问题，比如现在path是用字符串拼起来的，我知道这样不对。。

**Comment by Logiase** [comment]
> 所以我真的不是很熟悉windows的逻辑，真的希望你能帮我完善。。以及还有其他的一些问题，比如现在path是用字符串拼起来的，我知道这样不对。。

我先熟悉熟悉）

**Comment by Decodetalkers** [comment]
close as completed
