### ISSUE TITLE
bad CPU type in executable

### ISSUE THREAD

**Issue by Jackson-soft** [Decodetalkers/neocmakelsp#50]
![image](https://github.com/Decodetalkers/neocmakelsp/assets/3928114/f50ec932-6d02-46f0-b84d-2c018e46dbef)

![image](https://github.com/Decodetalkers/neocmakelsp/assets/3928114/68d63e16-522e-494b-9020-05398ceab904)

https://github.com/actions/runner-images

![image](https://github.com/Decodetalkers/neocmakelsp/assets/3928114/738fb9d3-9b15-44d2-a593-54019e2339dd)

Can you add intel CPU support?

**Comment by Decodetalkers** [comment]
macos-latest-large right? I will add it tonight

**Comment by Decodetalkers** [comment]
seems the ci won't work, do I do something wrong?

**Comment by Decodetalkers** [comment]
Emm.. but x64 is large..

**Comment by Decodetalkers** [comment]
do you think mac-12 is enough? Emm. I do not know if the target by mac-12 can be used on mac-14

**Comment by Jackson-soft** [comment]
we can do a test to see

**Comment by Jackson-soft** [comment]
![图片](https://github.com/Decodetalkers/neocmakelsp/assets/3928114/d80db5ed-a6b8-41b6-ba39-8cb7d30af699)


can work

**Comment by Jackson-soft** [comment]
This resolves #52
