### ISSUE TITLE
hasn't completion

### ISSUE THREAD

**Issue by gxt-kt** [Decodetalkers/neocmakelsp#55]
I install neocmakelsp by mason in neovim.
And when i open a cmake file, i can get the `grammar error` but `hasn't completion`.
I have add config with stdio like readme.( comment the on_attach line)
```lua
local configs = require("lspconfig.configs")
local nvim_lsp = require("lspconfig")
if not configs.neocmake then
    configs.neocmake = {
        default_config = {
            cmd = { "neocmakelsp", "--stdio" },
            filetypes = { "cmake" },
            root_dir = function(fname)
                return nvim_lsp.util.find_git_ancestor(fname)
            end,
            single_file_support = true,-- suggested
            -- on_attach = on_attach, -- on_attach is the on_attach function you defined
            init_options = {
                format = {
                    enable = true
                },
                scan_cmake_in_package = true -- default is true
            }
        }
    }
    nvim_lsp.neocmake.setup({})
end
```
Still like that,did i loss some package or details.

**Comment by Decodetalkers** [comment]
do you have install cmake?

**Comment by Decodetalkers** [comment]
gammer check is from treesitter, completion is from cmake and package search. so if there is no `cmake` command, it will not complete anything

**Comment by gxt-kt** [comment]
Wow！I am really a  idot.
I didn't install cmake because i'm config a new mac.
After installing cmake all things are normal.
Thanks for you a lot.
