### ISSUE TITLE
[feature] Diagnostic (linter)

### ISSUE THREAD

**Issue by Freed-Wu** [Decodetalkers/neocmakelsp#56]
Can it provide some linter feature like [cmakelint](https://pypi.org/project/cmakelint/) or [cmake-lint](https://pypi.org/project/cmake-format/)? For example, users shouldn't mix uppercase (e.g., `INSTALL()`) and lowercase `add_executable()`. if so, give them a warning.

**Comment by Decodetalkers** [comment]
Emm. then what will the config file be? toml or yaml, what is its name?

**Comment by Freed-Wu** [comment]
> what will the config file be? toml or yaml

Oh, it depends on you :smile:

**Comment by Decodetalkers** [comment]
what do you thought of this :
https://github.com/Decodetalkers/neocmakelsp/pull/57

**Comment by Decodetalkers** [comment]
> Can we have `neocmakelsp linter XXX.cmake` like `neocmakelsp format XXX.cmake`? And we can add a new pre-commit hook named `neocmakelsp-linter` like current `neocmakelsp-format`.

I would like to .. I also want to rewrite the cmake-lint, but now I do not have enough energy to do that..

**Comment by Freed-Wu** [comment]
> I also want to rewrite the cmake-lint

Can we reopen this issue as a feature request?

**Comment by Decodetalkers** [comment]
> > I also want to rewrite the cmake-lint
> 
> Can we reopen this issue as a feature request?

Yes, you can, but I do not know if I have the energy to finish this feature. You can help me finish this.
