### ISSUE TITLE
Disable linting in init_options

### ISSUE THREAD

**Issue by b0o** [Decodetalkers/neocmakelsp#87]
Great project, really liking it so far! Is there a way to disable linting from the lspconfig init_options? I am using another plugin for linting.

**Comment by Decodetalkers** [comment]
I have forgotten to set it. Now you can set it in

.neocmakelint.toml

```toml
command_upcase = "ignore"enable_external_cmake_lint = false
```

**Comment by b0o** [comment]
Thanks for the quick reply. Can I do it from the init options? I would rather not create another config file in my project just to disable linting for this LSP, which other devs on my project do not use.

**Comment by Decodetalkers** [comment]
If you can help pr it for me, I will feel very happy 😊, or I will finish it this night

**Comment by Decodetalkers** [comment]
do the newest commit solve your problem?

**Comment by b0o** [comment]
Yes, that works perfectly! Thank you!

**Comment by Decodetalkers** [comment]
new version published, now fixed
